{
  "Uuid": "2252df63-1f73-4164-8233-ade520d0e8e7",
  "IsCustomNode": false,
  "Description": null,
  "Name": "chess board points",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "18c0b184595a4a53ac698b2e7b5c2abf",
      "Inputs": [
        {
          "Id": "442499a1774344a18e1b58627778c1ef",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "62a8ed13864b447dafa2b0b4945e9e4a",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3137100b700748ee8616f45badbbea6c",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "0702c704e65d49d7ae371a758c2636f9",
      "Inputs": [
        {
          "Id": "43ff088adba249128057ba1a6ed020ec",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a11e54f51ddd41da9da2c58fe3e8be18",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9a87610814994cca8be09e13d11905ec",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "666bd3783e0943c9935018d4dc78439f",
      "Inputs": [
        {
          "Id": "aae954a0ec1c48fcaca788c574c64226",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8d749970ccc04f42b907a689aba53d24",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "45c120e86b2b4fdaa3d2da6b62931734",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "0f3f7f92ad944691a43f7760ee341fc4",
      "Inputs": [
        {
          "Id": "62e8b6a87a4244d7a55983ff163a5312",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "651d09583af444b18d90d0aa659d4377",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dfc76db0094245829fa86bc1d0c961b4",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c895670d10ad4ee0ac17eb2d4ab0cb98",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "96b5e720997b4d17bafa14f832882533",
      "Inputs": [
        {
          "Id": "d5234118f7de43dfa9c31fa1ee83518b",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d37c96e2c76b42f796f9f80875a4f453",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4e10180622d94a278e543d929f360d3c",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7ee8eee6dd934014a33fd0647dd4710f",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "a73bc5cc80574898be5bb2df0d205e8d",
      "Inputs": [
        {
          "Id": "ed846676ae544dd59c006f1387023e08",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "66d65282d8524b2fbaefbc3b8af4c5bf",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "acf04824a394489fa5363e21714e8e55",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "78c48ede123c4b7790ba331d60470f6b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 0.0,
      "Id": "45379ffe190547c69c3a6732610ca21d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f4c82f208129476c89c1a74a25815465",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 10.0,
      "Id": "ccc7d58ca6384c2e9739e93bcc3d4aac",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "cbfd88b1d057466fbb8928ce2a881b8a",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 15.0,
      "Id": "9156288d82684261a39f0913d1024c00",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "32542778311343658ceb36b0cf2be52c",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 2.0,
      "Id": "4a85a74a97464c8da42a14d6eae10940",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b9179036adf14c13b7a63ff8068bf0dc",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 5.0,
      "Id": "c64d0d540b424d00985ff2f5cbdf41cd",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "18e9420f628543749ad2591604e6bf3c",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 8.0,
      "Id": "2d276dfd0ac048ba9e1f65643ffd075e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "81d96aa1d7b849448a31819f64ef2e2e",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "4be60f03f1fd480dbca9c4876da6ebbb",
      "Inputs": [
        {
          "Id": "d4ada67c4b6d424aa0d9bb8e69ffcbb7",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "40dea8f06d7448c9b2a36ed72093b5c4",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "53962aba48904054a78f8a4f9f039039",
          "Name": "item2",
          "Description": "Item Index #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b0e603a310274cddbe03bb3ff52ad0b8",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "2958e149435345398b59f81cb89b91d0",
      "Inputs": [
        {
          "Id": "2ddaebda420a4e2c8ca8f1c3a010c81f",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7a0bd4870a914437adbff9c39a0d1b1e",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid by lofting between input cross section closed Curves.\n\nSolid.ByLoft (crossSections: Curve[]): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.Fillet@Autodesk.DesignScript.Geometry.Edge[],double",
      "Id": "2f17d9f58f834b38a0db880e9d78116a",
      "Inputs": [
        {
          "Id": "51d81d6ca11d417f9c76c09a259ba814",
          "Name": "solid",
          "Description": "Autodesk.DesignScript.Geometry.Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7eba3cf893d441f09a5c7c5a5ea47097",
          "Name": "edges",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cc4c482eb88b4e5c90636ea215b6c040",
          "Name": "radius",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ff2f4dac7d074dc591e62a894be2d5f2",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Fillets a Solid along input Edges with a given radius.\n\nSolid.Fillet (edges: Edge[], radius: double): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Edges",
      "Id": "93f752b77bf4453a94794806030d8c09",
      "Inputs": [
        {
          "Id": "19e79a88d94449e9af198f521ad0647a",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ffcc098b1998471b87cc5660f31e4c44",
          "Name": "Edge[]",
          "Description": "Edge[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Edges of the Topology\n\nTopology.Edges: Edge[]"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 50.0,
      "MinimumValue": 0.0,
      "StepValue": 1.0,
      "InputValue": 2.0,
      "Id": "6185aab9d7214f69b93a5a224fef8f58",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "61866c604dd8478fb6d02d1894c37f5b",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Solid.BySweep@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve",
      "Id": "6c4b723f263d4ed5acb41732690de9ce",
      "Inputs": [
        {
          "Id": "bd71710f338d44178639dfa9e40b1ca1",
          "Name": "profile",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7e8d7f1f950e4261a18048f83c788f5a",
          "Name": "path",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3636ed9c9c0e41ff835d0a26b7ac0160",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Sweep a closed Curve along a path.\n\nSolid.BySweep (profile: Curve, path: Curve): Solid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.TangentAtParameter@double",
      "Id": "3ab33fd65b354cddafd7e79955bcfc42",
      "Inputs": [
        {
          "Id": "7713f07cec0f42e1b0652c7ea2c80fdf",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f9aae8415c8242e19a07a524114a4b66",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e8831298fc6f4791a7f36d494b735d35",
          "Name": "Vector",
          "Description": "A Vector parallel to the curve at param",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Vector tangent to the curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.TangentAtParameter (param: double = 0): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "895e5bdabe83447192425f2339502403",
      "Inputs": [
        {
          "Id": "68195c7e099c42369b3f4da5ef0c35c9",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3b515065d5a84a039016606f556dba7c",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eeb6f16da4cf4ab9922b585ed20c25e1",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadiusNormal@Autodesk.DesignScript.Geometry.Point,double,Autodesk.DesignScript.Geometry.Vector",
      "Id": "3639e8d874434df0bd260dd249d4a159",
      "Inputs": [
        {
          "Id": "508d6e4e7df14c378fc0059d71ad2d8d",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "59b4f44cb3e842fda971cfef2d9b9f5f",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "822cb58ad22841d98789e0e3ffa28ccb",
          "Name": "normal",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ce29caeb949d43d4a3aabdcfa6d71934",
          "Name": "Circle",
          "Description": "Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Circle with specified center Point, radius, and normal direction.\n\nCircle.ByCenterPointRadiusNormal (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1, normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Circle"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 100.0,
      "MinimumValue": 0.0,
      "StepValue": 0.1,
      "InputValue": 0.75,
      "Id": "45031bd5427c4f62ab3a3da8e73a1231",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "34deb7b4acda4fae983cf5651b7d8605",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    }
  ],
  "Connectors": [
    {
      "Start": "3137100b700748ee8616f45badbbea6c",
      "End": "d4ada67c4b6d424aa0d9bb8e69ffcbb7",
      "Id": "4688121f59bd4d93bb5878bcbfb05d2f"
    },
    {
      "Start": "9a87610814994cca8be09e13d11905ec",
      "End": "40dea8f06d7448c9b2a36ed72093b5c4",
      "Id": "619bec24cfb64fa6ac95be6e484f6f75"
    },
    {
      "Start": "9a87610814994cca8be09e13d11905ec",
      "End": "7e8d7f1f950e4261a18048f83c788f5a",
      "Id": "3102d2cfef7745bab3f67f5da76bcd14"
    },
    {
      "Start": "9a87610814994cca8be09e13d11905ec",
      "End": "68195c7e099c42369b3f4da5ef0c35c9",
      "Id": "09058532965c49308af873d4899724d1"
    },
    {
      "Start": "9a87610814994cca8be09e13d11905ec",
      "End": "7713f07cec0f42e1b0652c7ea2c80fdf",
      "Id": "6a5646fceba44372947e8f069fcee4a2"
    },
    {
      "Start": "45c120e86b2b4fdaa3d2da6b62931734",
      "End": "53962aba48904054a78f8a4f9f039039",
      "Id": "fad8f7331dca4355897c029d9c70a117"
    },
    {
      "Start": "c895670d10ad4ee0ac17eb2d4ab0cb98",
      "End": "43ff088adba249128057ba1a6ed020ec",
      "Id": "1062c45dc0d24823ad9369620ec5b492"
    },
    {
      "Start": "7ee8eee6dd934014a33fd0647dd4710f",
      "End": "aae954a0ec1c48fcaca788c574c64226",
      "Id": "88d3d47bad49472bbd781204b7c847b6"
    },
    {
      "Start": "78c48ede123c4b7790ba331d60470f6b",
      "End": "442499a1774344a18e1b58627778c1ef",
      "Id": "6d8ec94a808b4d8380b6f9d38b91053a"
    },
    {
      "Start": "f4c82f208129476c89c1a74a25815465",
      "End": "acf04824a394489fa5363e21714e8e55",
      "Id": "18b39bf95e8543fa936390e9dd80bfd5"
    },
    {
      "Start": "cbfd88b1d057466fbb8928ce2a881b8a",
      "End": "dfc76db0094245829fa86bc1d0c961b4",
      "Id": "7ff92136bf4c488799a04b3f320db3a3"
    },
    {
      "Start": "32542778311343658ceb36b0cf2be52c",
      "End": "4e10180622d94a278e543d929f360d3c",
      "Id": "65155e741eb34659b22b5d492bbf55c0"
    },
    {
      "Start": "b9179036adf14c13b7a63ff8068bf0dc",
      "End": "a11e54f51ddd41da9da2c58fe3e8be18",
      "Id": "815a72128c3d48c5a46747db58e03bf8"
    },
    {
      "Start": "18e9420f628543749ad2591604e6bf3c",
      "End": "8d749970ccc04f42b907a689aba53d24",
      "Id": "55c65df95c9649aaa20d4c16ac582687"
    },
    {
      "Start": "81d96aa1d7b849448a31819f64ef2e2e",
      "End": "62a8ed13864b447dafa2b0b4945e9e4a",
      "Id": "a04e15fd577b42359f26a26490e9828f"
    },
    {
      "Start": "b0e603a310274cddbe03bb3ff52ad0b8",
      "End": "2ddaebda420a4e2c8ca8f1c3a010c81f",
      "Id": "775103dbfad0468f98534618ac8d69eb"
    },
    {
      "Start": "7a0bd4870a914437adbff9c39a0d1b1e",
      "End": "51d81d6ca11d417f9c76c09a259ba814",
      "Id": "1de05891fe74490aa6365efc0843a199"
    },
    {
      "Start": "7a0bd4870a914437adbff9c39a0d1b1e",
      "End": "19e79a88d94449e9af198f521ad0647a",
      "Id": "eb8e875b52c844cf89337ae5b442044a"
    },
    {
      "Start": "ffcc098b1998471b87cc5660f31e4c44",
      "End": "7eba3cf893d441f09a5c7c5a5ea47097",
      "Id": "a25679bb93d443d48090f33ac9e5a594"
    },
    {
      "Start": "61866c604dd8478fb6d02d1894c37f5b",
      "End": "cc4c482eb88b4e5c90636ea215b6c040",
      "Id": "e08e34086d6b4bde942207a46c09c181"
    },
    {
      "Start": "e8831298fc6f4791a7f36d494b735d35",
      "End": "822cb58ad22841d98789e0e3ffa28ccb",
      "Id": "fe7be13ba33245d293a74b4baa409027"
    },
    {
      "Start": "eeb6f16da4cf4ab9922b585ed20c25e1",
      "End": "508d6e4e7df14c378fc0059d71ad2d8d",
      "Id": "7f0c4434210b4c2c90a30693569a9836"
    },
    {
      "Start": "ce29caeb949d43d4a3aabdcfa6d71934",
      "End": "bd71710f338d44178639dfa9e40b1ca1",
      "Id": "21005c5cb540428882b747af4ac6916a"
    },
    {
      "Start": "34deb7b4acda4fae983cf5651b7d8605",
      "End": "59b4f44cb3e842fda971cfef2d9b9f5f",
      "Id": "7290c6f171794817b7ab4639008bbe17"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.5.0.7460",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -90.952898058267522,
      "EyeY": 99.639810140497246,
      "EyeZ": 87.585705339526072,
      "LookX": 108.70830843047096,
      "LookY": -82.250139143902885,
      "LookZ": -66.123317084609724,
      "UpX": 0.299204026576869,
      "UpY": 0.93667218924840356,
      "UpZ": -0.18199494599796967
    },
    "NodeViews": [
      {
        "Id": "18c0b184595a4a53ac698b2e7b5c2abf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByCenterPointRadius",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 360.09244669402278,
        "Y": 193.67204517796108
      },
      {
        "Id": "0702c704e65d49d7ae371a758c2636f9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByCenterPointRadius",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 361.85036750066433,
        "Y": 326.21244620582536
      },
      {
        "Id": "666bd3783e0943c9935018d4dc78439f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByCenterPointRadius",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 361.85036750066433,
        "Y": 454.54066509066155
      },
      {
        "Id": "0f3f7f92ad944691a43f7760ee341fc4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -307.97959402979586,
        "Y": 287.17396073844992
      },
      {
        "Id": "96b5e720997b4d17bafa14f832882533",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -307.26566338691396,
        "Y": 456.7950946051065
      },
      {
        "Id": "a73bc5cc80574898be5bb2df0d205e8d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -304.66709102962523,
        "Y": 118.9806881575559
      },
      {
        "Id": "45379ffe190547c69c3a6732610ca21d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -726.04231145609936,
        "Y": 172.17624046997349
      },
      {
        "Id": "ccc7d58ca6384c2e9739e93bcc3d4aac",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -729.82877068219454,
        "Y": 336.88721680510082
      },
      {
        "Id": "9156288d82684261a39f0913d1024c00",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -733.61522990828962,
        "Y": 516.7440300446076
      },
      {
        "Id": "4a85a74a97464c8da42a14d6eae10940",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -87.69456451246424,
        "Y": 389.39676485866704
      },
      {
        "Id": "c64d0d540b424d00985ff2f5cbdf41cd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -81.724971722057489,
        "Y": 530.6771275649653
      },
      {
        "Id": "2d276dfd0ac048ba9e1f65643ffd075e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -85.882274979975364,
        "Y": 248.03818132453756
      },
      {
        "Id": "4be60f03f1fd480dbca9c4876da6ebbb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List Create",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 765.70251305528006,
        "Y": 112.34039913605665
      },
      {
        "Id": "2958e149435345398b59f81cb89b91d0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.ByLoft",
        "ShowGeometry": false,
        "Excluded": false,
        "X": 996.634914866452,
        "Y": -67.0266798373305
      },
      {
        "Id": "2f17d9f58f834b38a0db880e9d78116a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.Fillet",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1603.1153700957664,
        "Y": -64.593379854716147
      },
      {
        "Id": "93f752b77bf4453a94794806030d8c09",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Edges",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1289.5505237836226,
        "Y": 25.212919818651869
      },
      {
        "Id": "6185aab9d7214f69b93a5a224fef8f58",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1205.9433009118331,
        "Y": 135.18614436662722
      },
      {
        "Id": "6c4b723f263d4ed5acb41732690de9ce",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Solid.BySweep",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1440.1870642366068,
        "Y": 459.73762488397171
      },
      {
        "Id": "3ab33fd65b354cddafd7e79955bcfc42",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.TangentAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 849.4185165656,
        "Y": 807.2662422218591
      },
      {
        "Id": "895e5bdabe83447192425f2339502403",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 845.18692101802947,
        "Y": 531.85916825433515
      },
      {
        "Id": "3639e8d874434df0bd260dd249d4a159",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Circle.ByCenterPointRadiusNormal",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1140.6393602504386,
        "Y": 638.9118687736709
      },
      {
        "Id": "45031bd5427c4f62ab3a3da8e73a1231",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Number Slider",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 774.948445462263,
        "Y": 688.01200991304086
      }
    ],
    "Annotations": [
      {
        "Id": "cbf993096c8748cb9838a023202cb74a",
        "Title": "Solid Loft",
        "Nodes": [
          "4be60f03f1fd480dbca9c4876da6ebbb",
          "2958e149435345398b59f81cb89b91d0",
          "2f17d9f58f834b38a0db880e9d78116a",
          "93f752b77bf4453a94794806030d8c09",
          "6185aab9d7214f69b93a5a224fef8f58"
        ],
        "Left": 755.70251305528006,
        "Top": -120.02667983733051,
        "Width": 1044.4128570404864,
        "Height": 377.36707897338715,
        "FontSize": 36.0,
        "InitialTop": -67.0266798373305,
        "InitialHeight": 354.36707897338715,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "4faa88cd02ce4983bef394f2ecbc01df",
        "Title": "Solid/Sweep",
        "Nodes": [
          "6c4b723f263d4ed5acb41732690de9ce",
          "3ab33fd65b354cddafd7e79955bcfc42",
          "895e5bdabe83447192425f2339502403",
          "3639e8d874434df0bd260dd249d4a159",
          "45031bd5427c4f62ab3a3da8e73a1231"
        ],
        "Left": 764.948445462263,
        "Top": 406.73762488397171,
        "Width": 873.23861877434388,
        "Height": 519.52861733788745,
        "FontSize": 36.0,
        "InitialTop": 459.73762488397171,
        "InitialHeight": 496.52861733788734,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 97.29716754852808,
    "Y": 222.82544936790794,
    "Zoom": 0.24336253885767906
  }
}